
logo: "/_media/alf-128.png"
title: Auto Load Forms
description: "Automatically fills and manages your forms (c) 2026 by chzb"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark  # Toto prepne tému na tmavú

header_pages: [] # Skryje automatické odkazy na iné stránky v menu
footer: ""       # Niektoré verzie Minimy na toto reagujú

show_downloads1: false
github1:
  is_project_page: false
include:
  - _media

github_username: 
twitter_username:
email:
# A ak nechceš ten feed:
plugins: [] 