
logo: "/_media/alf-128.png"
title: Auto Load Forms
footer: "Automatically fills and manages your forms (c) 2026 by chzb"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark  # Toto prepne tému na tmavú

include:
  - _media

header_pages: []
footer_show_posts: false
social_links: []